- name: download packer
  get_url: url=https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip dest=/tmp/packer.zip
  register: packer_was_downloaded

- name: unzip packer
  unarchive:
    copy: no
    creates: /usr/local/bin/packer
    src: /tmp/packer.zip
    dest: /usr/local/bin
  when: packer_was_downloaded|changed

